display_name:  Codewithwest Admin
package_name: codewithwest-admin

maintainer:
  name: Jon West
  email: westdynamics.tech@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - mpv

essential: false

# icon: linux/assets/images/flutter_logo.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Admin
  - Admin Client

generic_name: API Client

categories:
  - Management
  - Development
  - Admin
  - Admin Client
  - Admin Management
  - Admin Utility
  - Development Utility
  - Management Utility
  - Utility

startup_notify: true