name: Docker Image CI

on:
  push:
    branches: ["platform"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build and tag the Docker image
        run: |
          IMAGE_TAG=3.29.0
          docker build . --file Dockerfile --tag codewithwest-flutter:$IMAGE_TAG
          docker tag codewithwest-flutter:$IMAGE_TAG ghcr.io/${{ github.repository }}/codewithwest-flutter:$IMAGE_TAG
          docker push ghcr.io/${{ github.repository }}/codewithwest-flutter:$IMAGE_TAG
