name: Codewithwest admin deb package

on:
  push:
    branches:
      - dev
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.x"
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev -y

          flutter pub get
          dart pub global activate flutter_distributor

      - name: Build debian package
        run: |
          flutter_distributor release --name=prod --jobs=release-prod-linux-deb
          ls -la dist/ # Check the dist directory

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: codewithwest-admin
          path: dist/*/*.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Debian package
        uses: actions/download-artifact@v4
        with:
          name: codewithwest-admin
          path: dist/

      - name: Get package name
        id: get_package_name
        run: |
          PACKAGE_NAME=$(ls .dist/.deb)
          echo "PACKAGE_NAME=$(basename $PACKAGE_NAME)" >> $GITHUB_OUTPUT

      - name: Attach to Release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            const artifactPath = `./${{ steps.get_package_name.outputs.PACKAGE_NAME }}`;
            const artifactContent = await fs.readFile(artifactPath);

            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: '${{ steps.get_package_name.outputs.PACKAGE_NAME }}',
              data: artifactContent,
            });
